<?xml version="1.0" encoding="UTF-8" ?>    
<teamtalk>
    <host>
    <name>ESTILO-V2</name>
    <address>103.157.116.41</address>
    <tcpport>11111</tcpport>
    <udpport>11111</udpport>
    <encrypted>true</encrypted>
    <auth>
        <username></username>
        <password></password>
        </auth>
        <join>
            <channel>/</channel>
        <password></password>
        </join>
        </host>
        <host>
            <name>ESTILO-NEW</name>
            <address>103.140.55.77</address>
            <tcpport>22222</tcpport>
            <udpport>22222</udpport>
            <encrypted>true</encrypted>
            <auth>
                <username>user</username>
                <password></password>
                </auth>
                <join><channel>/</channel>
                <password></password></join>
                </host>
                <host>
                    <name>ESTILO NEW</name>
                    <address>103.140.55.77</address>
                    <tcpport>22222</tcpport>
                    <udpport>22222</udpport>
                    <encrypted>true</encrypted>
                    <auth>
                        <username></username>
                        <password></password>
                        </auth>
                        <join>
                            <channel>/</channel>
                            <password></password>
                            </join>
                            </host>
                            <host>
                            <name>RPV</name>
                            <address>202.157.177.180</address>
                            <tcpport>10333</tcpport>
                            <udpport>10333</udpport>
                            <encrypted>true</encrypted>
                            <auth>
                                <username></username>
                                <password></password>
                                </auth>
                                <join>
                                    <channel>/</channel>
                                    <password></password>
                                    </join>
                                    </host>
                                    </teamtalk>
